//! Regenerate `src/block_ids.rs` from azalea's state tables.
//!
//! Run after any azalea (= MC protocol) version bump:
//!
//! ```sh
//! cargo run --example gen_block_ids
//! ```
//!
//! `tests/block_ids.rs` fails whenever the checked-in file disagrees with
//! the compiled azalea version, so a forgotten regeneration cannot ship.

use std::fmt::Write as _;
use std::path::Path;

use ultimate_server::registry;

fn main() {
    let mut out = String::new();
    writeln!(
        out,
        "//! GENERATED by `cargo run --example gen_block_ids` — DO NOT EDIT.\n\
         //!\n\
         //! Block-state ids for MC {} (protocol {}), derived from azalea's\n\
         //! state tables via `registry::GENERATED_DEFAULTS`. Rerun the\n\
         //! generator after an azalea version bump; `tests/block_ids.rs`\n\
         //! guards against drift.\n\
         \nuse ultimate_engine::world::block::BlockId;\n",
        azalea_protocol::packets::VERSION_NAME,
        azalea_protocol::packets::PROTOCOL_VERSION,
    )
    .unwrap();

    for (const_name, block_name) in registry::GENERATED_DEFAULTS {
        let id = registry::block_id_from_name(block_name)
            .unwrap_or_else(|| panic!("{block_name} must resolve"));
        writeln!(
            out,
            "/// Default state of `minecraft:{block_name}`.\n\
             pub const {const_name}: BlockId = BlockId({});",
            id.0
        )
        .unwrap();
    }

    for (arr_name, fluid) in [("WATER_LEVEL_IDS", "water"), ("LAVA_LEVEL_IDS", "lava")] {
        let ids = registry::fluid_level_ids(fluid);
        writeln!(
            out,
            "\n/// `minecraft:{fluid}[level=N]` state ids, indexed by level.\n\
             pub const {arr_name}: [u16; 16] = {ids:?};"
        )
        .unwrap();
    }

    writeln!(
        out,
        "\n/// The full manifest as data, for the drift-guard test.\n\
         pub const GENERATED_TABLE: &[(&str, u16)] = &["
    )
    .unwrap();
    for (const_name, block_name) in registry::GENERATED_DEFAULTS {
        let id = registry::block_id_from_name(block_name).unwrap();
        writeln!(out, "    (\"{const_name}\", {}),", id.0).unwrap();
    }
    writeln!(out, "];").unwrap();

    let dest = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/block_ids.rs");
    std::fs::write(&dest, &out).expect("write block_ids.rs");
    println!("wrote {}", dest.display());
}
