//! GENERATED by `cargo run --example gen_block_ids` — DO NOT EDIT.
//!
//! Block-state ids for MC 26.1 (protocol 775), derived from azalea's
//! state tables via `registry::GENERATED_DEFAULTS`. Rerun the
//! generator after an azalea version bump; `tests/block_ids.rs`
//! guards against drift.

use ultimate_engine::world::block::BlockId;

/// Default state of `minecraft:air`.
pub const AIR: BlockId = BlockId(0);
/// Default state of `minecraft:stone`.
pub const STONE: BlockId = BlockId(1);
/// Default state of `minecraft:grass_block`.
pub const GRASS_BLOCK: BlockId = BlockId(9);
/// Default state of `minecraft:dirt`.
pub const DIRT: BlockId = BlockId(10);
/// Default state of `minecraft:bedrock`.
pub const BEDROCK: BlockId = BlockId(85);
/// Default state of `minecraft:sand`.
pub const SAND: BlockId = BlockId(118);
/// Default state of `minecraft:oak_log`.
pub const OAK_LOG: BlockId = BlockId(137);
/// Default state of `minecraft:oak_leaves`.
pub const LEAVES: BlockId = BlockId(279);
/// Default state of `minecraft:water`.
pub const WATER: BlockId = BlockId(86);
/// Default state of `minecraft:lava`.
pub const LAVA: BlockId = BlockId(102);

/// `minecraft:water[level=N]` state ids, indexed by level.
pub const WATER_LEVEL_IDS: [u16; 16] = [86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101];

/// `minecraft:lava[level=N]` state ids, indexed by level.
pub const LAVA_LEVEL_IDS: [u16; 16] = [102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117];

/// The full manifest as data, for the drift-guard test.
pub const GENERATED_TABLE: &[(&str, u16)] = &[
    ("AIR", 0),
    ("STONE", 1),
    ("GRASS_BLOCK", 9),
    ("DIRT", 10),
    ("BEDROCK", 85),
    ("SAND", 118),
    ("OAK_LOG", 137),
    ("LEAVES", 279),
    ("WATER", 86),
    ("LAVA", 102),
];
